"""Generate reflected Data Asset properties and the tuning reference from the schema."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
source = (ROOT / 'Source/Combat/Public/CombatLocomotionParameters.inl').read_text(encoding='utf-8')
rows = []
for line in source.splitlines():
    match = re.fullmatch(r'LOCO_(FLOAT|BOOL)\((\w+), (\w+), (\w+), ([^,]+), (.*)\)', line)
    if not match:
        continue
    kind, member, section, key, default, rest = match.groups()
    if kind == 'FLOAT':
        lo, hi, description = rest.split(', ', 2)
        limits = f'{lo}～{hi}'
    else:
        description, limits = rest, 'true / false'
        lo, hi = '0', '1'
    rows.append((section, key, default, limits, description.strip('"'), kind, member, lo, hi))

categories = dict(zip(('Movement', 'Pivot', 'Animation', 'Air', 'Dash', 'SkillBlend', 'Camera', 'Debug'),
                     ('01 Movement 移动', '02 Pivot 折返', '03 Animation 动画', '04 Air 空中',
                      '05 Dash 闪避', '06 SkillBlend 技能融合', '07 Camera 相机', '08 Debug 调试')))
header = ['// Generated by Tools/editor/generate_locomotion_config.py. Edit the .inl schema, then regenerate.',
          '#pragma once', '#include "CoreMinimal.h"', '#include "Engine/DataAsset.h"',
          '#include "CombatLocomotionValues.h"', '#include "CombatLocomotionConfig.generated.h"', '',
          '/** Edit this asset in Details, including during PIE. Save the asset to keep your tuning. */',
          'UCLASS(BlueprintType)', 'class COMBAT_API UCombatLocomotionConfig : public UDataAsset', '{',
          '    GENERATED_BODY()', 'public:', '    FCombatLocomotionSettings MakeSnapshot() const;', '']
doc = ['# Locomotion 实时参数表', '',
       '配置资产：`/Game/Combat/Config/DA_Locomotion`（CombatLocomotionConfig Data Asset）。',
       '在内容浏览器双击资产，在 Details 面板按分类调参。PIE 中修改数值约 0.2 秒内生效，无需先保存；结束 PIE 后 Ctrl+S 保存，跨会话保留。',
       '玩家蓝图的 `Locomotion Config` 已绑定此资产；运行时不再读取 INI。',
       '控制台命令 `Combat.Locomotion.Reload` 可立即重载。屏幕显示配置版本、速度、加速度、Pivot 阶段。',
       'Details 提供数值范围约束和中文提示。字段之间的关系错误时保留上次有效配置，修正后自动恢复。', '',
       '默认 Pivot：以 900 cm/s² 刹车，转向速度 900°/s；刹停且朝向达标后以 1200 cm/s² 反向加速。',
       '反向加速可以发生在完整 Pivot 动画播放期间。素材不裁剪，播放倍率默认 1；EarlyExitEnabled 默认关闭。',
       '调小 BrakingDeceleration 会延长刹车；调大 ReverseAcceleration 会更快反向起步；TurnRate 控制转向快慢。', '',
       '仅作用于玩家。碰撞、重力、地面检测仍由 CharacterMovement 处理；技能可打断所有 Pivot 阶段。',
       '修改倍率/转向/加速度可作用于正在进行的动作；BlendIn 只影响下次入场，已经开始的淡出不重新计时。',
       '骨骼、片段引用、技能伤害/判定通知等仍属于原资产。动画图的 Grounded/Airborne 状态过渡在 ABP 中调整。', '',
       '| 分类 | 键 | 默认值 | 范围 | 说明 |', '|---|---|---:|---|---|']
for index, (group, key, default, limits, description, kind, member, lo, hi) in enumerate(rows):
    label = description.split('；')[0].split('，')[0]
    metadata = [f'DisplayName="{key} - {label}"', f'ToolTip="{description}"', f'DisplayPriority="{index}"']
    if kind == 'FLOAT':
        metadata += [f'ClampMin="{lo}"', f'ClampMax="{hi}"', f'UIMin="{lo}"', f'UIMax="{hi}"']
    header.append(f'    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="{categories[group]}", meta=({", ".join(metadata)}))')
    header.append(f'    {"float" if kind == "FLOAT" else "bool"} {member} = {str(float(default)) + "f" if kind == "FLOAT" else default};')
    doc.append(f'| {group} | `{key}` | {default} | {limits} | {description} |')
header.append('};')
(ROOT / 'Source/Combat/Public/CombatLocomotionConfig.h').write_text('\n'.join(header) + '\n', encoding='utf-8')
(ROOT / 'Docs/LocomotionParameters.md').write_text('\n'.join(doc) + '\n', encoding='utf-8')
print(f'{len(rows)} reflected locomotion properties and documentation generated; asset values are not modified')
