// Generated by Tools/editor/generate_locomotion_config.py. Edit the .inl schema, then regenerate.
#pragma once
#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "CombatLocomotionValues.h"
#include "CombatLocomotionConfig.generated.h"

/** Edit this asset in Details, including during PIE. Save the asset to keep your tuning. */
UCLASS(BlueprintType)
class COMBAT_API UCombatLocomotionConfig : public UDataAsset
{
    GENERATED_BODY()
public:
    FCombatLocomotionSettings MakeSnapshot() const;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="01 Movement 移动", meta=(DisplayName="ForwardSpeed - 前进最高速度 cm/s", ToolTip="前进最高速度 cm/s", DisplayPriority="0", ClampMin="1", ClampMax="3000", UIMin="1", UIMax="3000"))
    float ForwardSpeed = 560.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="01 Movement 移动", meta=(DisplayName="BackwardSpeed - 后退最高速度 cm/s", ToolTip="后退最高速度 cm/s", DisplayPriority="1", ClampMin="1", ClampMax="3000", UIMin="1", UIMax="3000"))
    float BackwardSpeed = 560.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="01 Movement 移动", meta=(DisplayName="LeftSpeed - 左移最高速度 cm/s", ToolTip="左移最高速度 cm/s", DisplayPriority="2", ClampMin="1", ClampMax="3000", UIMin="1", UIMax="3000"))
    float LeftSpeed = 560.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="01 Movement 移动", meta=(DisplayName="RightSpeed - 右移最高速度 cm/s", ToolTip="右移最高速度 cm/s", DisplayPriority="3", ClampMin="1", ClampMax="3000", UIMin="1", UIMax="3000"))
    float RightSpeed = 560.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="01 Movement 移动", meta=(DisplayName="Acceleration - 普通移动加速度 cm/s²", ToolTip="普通移动加速度 cm/s²", DisplayPriority="4", ClampMin="1", ClampMax="20000", UIMin="1", UIMax="20000"))
    float Acceleration = 1600.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="01 Movement 移动", meta=(DisplayName="GroundFriction - 普通移动转向摩擦", ToolTip="普通移动转向摩擦", DisplayPriority="5", ClampMin="0", ClampMax="50", UIMin="0", UIMax="50"))
    float GroundFriction = 4.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="01 Movement 移动", meta=(DisplayName="BrakingDeceleration - 松键刹车减速度 cm/s²", ToolTip="松键刹车减速度 cm/s²", DisplayPriority="6", ClampMin="0", ClampMax="20000", UIMin="0", UIMax="20000"))
    float BrakingDeceleration = 1200.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="01 Movement 移动", meta=(DisplayName="BrakingFriction - 松键独立刹车摩擦", ToolTip="松键独立刹车摩擦", DisplayPriority="7", ClampMin="0", ClampMax="50", UIMin="0", UIMax="50"))
    float BrakingFriction = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="01 Movement 移动", meta=(DisplayName="BrakingFrictionFactor - 普通刹车摩擦倍率", ToolTip="普通刹车摩擦倍率", DisplayPriority="8", ClampMin="0", ClampMax="10", UIMin="0", UIMax="10"))
    float BrakingFrictionFactor = 1.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="01 Movement 移动", meta=(DisplayName="TurnRate - 自由移动转向角速度 °/s", ToolTip="自由移动转向角速度 °/s", DisplayPriority="9", ClampMin="1", ClampMax="3600", UIMin="1", UIMax="3600"))
    float TurnRate = 900.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="01 Movement 移动", meta=(DisplayName="LockedTurnInterpSpeed - 锁定目标时朝向插值速度", ToolTip="锁定目标时朝向插值速度", DisplayPriority="10", ClampMin="0.1", ClampMax="100", UIMin="0.1", UIMax="100"))
    float LockedTurnInterpSpeed = 12.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="01 Movement 移动", meta=(DisplayName="InputDeadZone - 移动输入死区", ToolTip="移动输入死区", DisplayPriority="11", ClampMin="0", ClampMax="0.95", UIMin="0", UIMax="0.95"))
    float InputDeadZone = 0.01f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="Enabled - 启用折返", ToolTip="启用折返", DisplayPriority="12"))
    bool PivotEnabled = true;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="MinSpeed - 折返触发最低水平速度 cm/s", ToolTip="折返触发最低水平速度 cm/s", DisplayPriority="13", ClampMin="0", ClampMax="3000", UIMin="0", UIMax="3000"))
    float PivotMinSpeed = 160.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="MinAngle - 速度与新输入夹角阈值 °", ToolTip="速度与新输入夹角阈值 °", DisplayPriority="14", ClampMin="90", ClampMax="180", UIMin="90", UIMax="180"))
    float PivotMinAngle = 120.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="Cooldown - 折返结束或打断后冷却 s", ToolTip="折返结束或打断后冷却 s", DisplayPriority="15", ClampMin="0", ClampMax="5", UIMin="0", UIMax="5"))
    float PivotCooldown = 0.25f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="CancelAngle - 新输入偏离折返目标多少度时取消 °", ToolTip="新输入偏离折返目标多少度时取消 °", DisplayPriority="16", ClampMin="1", ClampMax="180", UIMin="1", UIMax="180"))
    float PivotCancelAngle = 60.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="CancelOnRelease - 松键是否取消折返", ToolTip="松键是否取消折返", DisplayPriority="17"))
    bool PivotCancelOnRelease = true;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="CancelOnLockChange - 切换锁定是否取消折返", ToolTip="切换锁定是否取消折返", DisplayPriority="18"))
    bool PivotCancelOnLockChange = true;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="BrakingDeceleration - 折返刹车减速度 cm/s²", ToolTip="折返刹车减速度 cm/s²；560速度约0.62秒刹停", DisplayPriority="19", ClampMin="1", ClampMax="20000", UIMin="1", UIMax="20000"))
    float PivotBrakingDeceleration = 900.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="BrakingFriction - 折返刹车附加摩擦", ToolTip="折返刹车附加摩擦；0为纯恒定减速度", DisplayPriority="20", ClampMin="0", ClampMax="50", UIMin="0", UIMax="50"))
    float PivotBrakingFriction = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="StopSpeed - 低于此速度允许切换反向加速 cm/s", ToolTip="低于此速度允许切换反向加速 cm/s", DisplayPriority="21", ClampMin="0", ClampMax="100", UIMin="0", UIMax="100"))
    float PivotStopSpeed = 5.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="ReverseAcceleration - 折返反向起步加速度 cm/s²", ToolTip="折返反向起步加速度 cm/s²", DisplayPriority="22", ClampMin="1", ClampMax="20000", UIMin="1", UIMax="20000"))
    float PivotReverseAcceleration = 1200.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="ReverseFriction - 反向加速阶段转向摩擦", ToolTip="反向加速阶段转向摩擦", DisplayPriority="23", ClampMin="0", ClampMax="50", UIMin="0", UIMax="50"))
    float PivotReverseFriction = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="ReverseDelay - 触发后允许反向起步的最早时间 s", ToolTip="触发后允许反向起步的最早时间 s", DisplayPriority="24", ClampMin="0", ClampMax="10", UIMin="0", UIMax="10"))
    float PivotReverseDelay = 0.1f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="ReverseMinProgress - 反向起步所需最小动画进度 0..1", ToolTip="反向起步所需最小动画进度 0..1", DisplayPriority="25", ClampMin="0", ClampMax="1", UIMin="0", UIMax="1"))
    float PivotReverseMinProgress = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="ReverseMaxFacingAngle - 自由移动时朝向距目标小于此角才允许反向起步 °", ToolTip="自由移动时朝向距目标小于此角才允许反向起步 °", DisplayPriority="26", ClampMin="0", ClampMax="180", UIMin="0", UIMax="180"))
    float PivotReverseMaxFacingAngle = 45.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="TurnDelay - 触发后延迟多久开始转向 s", ToolTip="触发后延迟多久开始转向 s", DisplayPriority="27", ClampMin="0", ClampMax="10", UIMin="0", UIMax="10"))
    float PivotTurnDelay = 0.02f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="TurnRate - 折返转向角速度 °/s", ToolTip="折返转向角速度 °/s；不再绑到整个片段时长", DisplayPriority="28", ClampMin="1", ClampMax="3600", UIMin="1", UIMax="3600"))
    float PivotTurnRate = 900.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="PlayRate - 完整Pivot片段播放倍率", ToolTip="完整Pivot片段播放倍率；不会裁剪源片段", DisplayPriority="29", ClampMin="0.05", ClampMax="4", UIMin="0.05", UIMax="4"))
    float PivotPlayRate = 1.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="BlendIn - Pivot进入融合 s", ToolTip="Pivot进入融合 s；下次触发生效", DisplayPriority="30", ClampMin="0", ClampMax="2", UIMin="0", UIMax="2"))
    float PivotBlendIn = 0.07f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="BlendOut - Pivot自然结束融合 s", ToolTip="Pivot自然结束融合 s", DisplayPriority="31", ClampMin="0", ClampMax="2", UIMin="0", UIMax="2"))
    float PivotBlendOut = 0.14f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="InterruptBlendOut - Pivot被技能等打断时融合 s", ToolTip="Pivot被技能等打断时融合 s", DisplayPriority="32", ClampMin="0", ClampMax="2", UIMin="0", UIMax="2"))
    float PivotInterruptBlendOut = 0.08f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="BlendOutTriggerTime - 距片尾多久开始融合 s", ToolTip="距片尾多久开始融合 s；0播完整段；-1自动", DisplayPriority="33", ClampMin="-1", ClampMax="5", UIMin="-1", UIMax="5"))
    float PivotBlendOutTriggerTime = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="EarlyExitEnabled - 反向达到速度后是否提前融合回locomotion", ToolTip="反向达到速度后是否提前融合回locomotion；默认完整播放", DisplayPriority="34"))
    bool PivotEarlyExit = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="ExitMinProgress - 提前退出所需最小动画进度", ToolTip="提前退出所需最小动画进度", DisplayPriority="35", ClampMin="0", ClampMax="1", UIMin="0", UIMax="1"))
    float PivotExitMinProgress = 0.65f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="02 Pivot 折返", meta=(DisplayName="ExitMinSpeed - 提前退出所需反向速度 cm/s", ToolTip="提前退出所需反向速度 cm/s", DisplayPriority="36", ClampMin="0", ClampMax="3000", UIMin="0", UIMax="3000"))
    float PivotExitMinSpeed = 350.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="03 Animation 动画", meta=(DisplayName="PlayRate - 地面BlendSpace播放倍率", ToolTip="地面BlendSpace播放倍率；独立于技能和Pivot", DisplayPriority="37", ClampMin="0.05", ClampMax="4", UIMin="0.05", UIMax="4"))
    float AnimationPlayRate = 1.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="03 Animation 动画", meta=(DisplayName="JogSpeed - 真实速度达到此值时到达Jog采样位置 cm/s", ToolTip="真实速度达到此值时到达Jog采样位置 cm/s", DisplayPriority="38", ClampMin="1", ClampMax="3000", UIMin="1", UIMax="3000"))
    float AnimationJogSpeed = 350.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="03 Animation 动画", meta=(DisplayName="FastSpeed - 真实速度达到此值时到达最高速度采样位置 cm/s", ToolTip="真实速度达到此值时到达最高速度采样位置 cm/s", DisplayPriority="39", ClampMin="2", ClampMax="4000", UIMin="2", UIMax="4000"))
    float AnimationFastSpeed = 650.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="03 Animation 动画", meta=(DisplayName="SpeedInterp - 动画速度参数平滑强度", ToolTip="动画速度参数平滑强度；0立即更新", DisplayPriority="40", ClampMin="0", ClampMax="100", UIMin="0", UIMax="100"))
    float AnimationSpeedInterp = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="03 Animation 动画", meta=(DisplayName="DirectionInterp - 动画方向参数平滑强度", ToolTip="动画方向参数平滑强度；0立即更新", DisplayPriority="41", ClampMin="0", ClampMax="100", UIMin="0", UIMax="100"))
    float AnimationDirectionInterp = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="03 Animation 动画", meta=(DisplayName="IdleDirectionSpeed - 低于此速度保持上次动画方向", ToolTip="低于此速度保持上次动画方向，避免停步抖动 cm/s", DisplayPriority="42", ClampMin="0", ClampMax="100", UIMin="0", UIMax="100"))
    float AnimationIdleDirectionSpeed = 5.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="04 Air 空中", meta=(DisplayName="JumpVelocity - 起跳速度 cm/s", ToolTip="起跳速度 cm/s", DisplayPriority="43", ClampMin="1", ClampMax="3000", UIMin="1", UIMax="3000"))
    float JumpVelocity = 650.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="04 Air 空中", meta=(DisplayName="GravityScale - 重力倍率", ToolTip="重力倍率", DisplayPriority="44", ClampMin="0.01", ClampMax="10", UIMin="0.01", UIMax="10"))
    float GravityScale = 1.8f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="04 Air 空中", meta=(DisplayName="AirControl - 空中控制比例", ToolTip="空中控制比例", DisplayPriority="45", ClampMin="0", ClampMax="1", UIMin="0", UIMax="1"))
    float AirControl = 0.7f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="04 Air 空中", meta=(DisplayName="BrakingDeceleration - 空中刹车减速度 cm/s²", ToolTip="空中刹车减速度 cm/s²", DisplayPriority="46", ClampMin="0", ClampMax="20000", UIMin="0", UIMax="20000"))
    float AirBrakingDeceleration = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="04 Air 空中", meta=(DisplayName="LateralFriction - 空中横向摩擦", ToolTip="空中横向摩擦", DisplayPriority="47", ClampMin="0", ClampMax="50", UIMin="0", UIMax="50"))
    float AirLateralFriction = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="04 Air 空中", meta=(DisplayName="JumpCount - 最大跳跃次数", ToolTip="最大跳跃次数，取整数", DisplayPriority="48", ClampMin="1", ClampMax="10", UIMin="1", UIMax="10"))
    float JumpCount = 2.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="04 Air 空中", meta=(DisplayName="MaxHangBudget - 空中攻击最大滞空预算 s", ToolTip="空中攻击最大滞空预算 s", DisplayPriority="49", ClampMin="0", ClampMax="2", UIMin="0", UIMax="2"))
    float MaxAirHangBudget = 0.25f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="04 Air 空中", meta=(DisplayName="PlungeHoldTime - 空中长按攻击触发下劈的时间 s", ToolTip="空中长按攻击触发下劈的时间 s", DisplayPriority="50", ClampMin="0", ClampMax="3", UIMin="0", UIMax="3"))
    float PlungeHoldTime = 0.28f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="05 Dash 闪避", meta=(DisplayName="Distance - 闪避移动距离 cm", ToolTip="闪避移动距离 cm", DisplayPriority="51", ClampMin="1", ClampMax="3000", UIMin="1", UIMax="3000"))
    float DashDistance = 250.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="05 Dash 闪避", meta=(DisplayName="Duration - 闪避移动时长 s", ToolTip="闪避移动时长 s；上限匹配当前0.255秒技能结束通知", DisplayPriority="52", ClampMin="0.01", ClampMax="0.25", UIMin="0.01", UIMax="0.25"))
    float DashDuration = 0.23f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="05 Dash 闪避", meta=(DisplayName="DirectionStep - 闪避方向量化角度 °", ToolTip="闪避方向量化角度 °", DisplayPriority="53", ClampMin="1", ClampMax="180", UIMin="1", UIMax="180"))
    float DashDirectionStep = 45.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="06 SkillBlend 技能融合", meta=(DisplayName="StopOnGroundSkill - 地面技能开始时是否清零普通移动速度", ToolTip="地面技能开始时是否清零普通移动速度", DisplayPriority="54"))
    bool StopOnGroundSkill = true;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="06 SkillBlend 技能融合", meta=(DisplayName="AllowMovementRecovery - 总开关：允许移动取消已开放取消窗口的普攻后摇", ToolTip="总开关：允许移动取消已开放取消窗口的普攻后摇", DisplayPriority="55"))
    bool AllowMovementRecovery = true;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="06 SkillBlend 技能融合", meta=(DisplayName="InputBufferTime - 技能输入缓存时间 s", ToolTip="技能输入缓存时间 s", DisplayPriority="56", ClampMin="0", ClampMax="1", UIMin="0", UIMax="1"))
    float InputBufferTime = 0.18f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="06 SkillBlend 技能融合", meta=(DisplayName="OverrideBlendOut - 由本表覆盖玩家技能结束和打断融合时间", ToolTip="由本表覆盖玩家技能结束和打断融合时间", DisplayPriority="57"))
    bool OverrideSkillBlendOut = true;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="06 SkillBlend 技能融合", meta=(DisplayName="LocomotionBlendOut - 玩家技能正常结束回移动的融合时间 s", ToolTip="玩家技能正常结束回移动的融合时间 s", DisplayPriority="58", ClampMin="0", ClampMax="2", UIMin="0", UIMax="2"))
    float SkillLocomotionBlendOut = 0.14f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="06 SkillBlend 技能融合", meta=(DisplayName="InterruptBlendOut - 玩家技能被打断融合时间 s", ToolTip="玩家技能被打断融合时间 s", DisplayPriority="59", ClampMin="0", ClampMax="2", UIMin="0", UIMax="2"))
    float SkillInterruptBlendOut = 0.08f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="Distance - 自由镜头距离 cm", ToolTip="自由镜头距离 cm", DisplayPriority="60", ClampMin="50", ClampMax="3000", UIMin="50", UIMax="3000"))
    float CameraDistance = 560.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="OffsetX - 镜头SocketOffset X cm", ToolTip="镜头SocketOffset X cm", DisplayPriority="61", ClampMin="-1000", ClampMax="1000", UIMin="-1000", UIMax="1000"))
    float CameraOffsetX = 0.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="OffsetY - 镜头SocketOffset Y cm", ToolTip="镜头SocketOffset Y cm", DisplayPriority="62", ClampMin="-1000", ClampMax="1000", UIMin="-1000", UIMax="1000"))
    float CameraOffsetY = 45.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="OffsetZ - 镜头SocketOffset Z cm", ToolTip="镜头SocketOffset Z cm", DisplayPriority="63", ClampMin="-1000", ClampMax="1000", UIMin="-1000", UIMax="1000"))
    float CameraOffsetZ = 85.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="FOV - 视野角 °", ToolTip="视野角 °", DisplayPriority="64", ClampMin="30", ClampMax="140", UIMin="30", UIMax="140"))
    float CameraFOV = 90.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="Sensitivity - 鼠标镜头灵敏度", ToolTip="鼠标镜头灵敏度", DisplayPriority="65", ClampMin="0.01", ClampMax="10", UIMin="0.01", UIMax="10"))
    float CameraSensitivity = 1.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="Collision - 镜头碰撞开关", ToolTip="镜头碰撞开关", DisplayPriority="66"))
    bool CameraCollision = true;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="ProbeSize - 镜头碰撞探针半径 cm", ToolTip="镜头碰撞探针半径 cm", DisplayPriority="67", ClampMin="1", ClampMax="100", UIMin="1", UIMax="100"))
    float CameraProbeSize = 12.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="PositionLag - 镜头位置延迟开关", ToolTip="镜头位置延迟开关", DisplayPriority="68"))
    bool CameraLag = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="PositionLagSpeed - 镜头位置延迟跟随速度", ToolTip="镜头位置延迟跟随速度", DisplayPriority="69", ClampMin="0.1", ClampMax="100", UIMin="0.1", UIMax="100"))
    float CameraLagSpeed = 10.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="RotationLag - 镜头旋转延迟开关", ToolTip="镜头旋转延迟开关", DisplayPriority="70"))
    bool CameraRotationLag = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="RotationLagSpeed - 镜头旋转延迟跟随速度", ToolTip="镜头旋转延迟跟随速度", DisplayPriority="71", ClampMin="0.1", ClampMax="100", UIMin="0.1", UIMax="100"))
    float CameraRotationLagSpeed = 10.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="LockedTargetWeight - 锁定构图中心向目标偏移比例", ToolTip="锁定构图中心向目标偏移比例", DisplayPriority="72", ClampMin="0", ClampMax="1", UIMin="0", UIMax="1"))
    float CameraLockedTargetWeight = 0.4f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="LockedPitchMin - 锁定镜头最小俯仰角 °", ToolTip="锁定镜头最小俯仰角 °", DisplayPriority="73", ClampMin="-89", ClampMax="89", UIMin="-89", UIMax="89"))
    float CameraPitchMin = -35.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="LockedPitchMax - 锁定镜头最大俯仰角 °", ToolTip="锁定镜头最大俯仰角 °", DisplayPriority="74", ClampMin="-89", ClampMax="89", UIMin="-89", UIMax="89"))
    float CameraPitchMax = -8.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="LockedRotationInterp - 锁定镜头旋转插值强度", ToolTip="锁定镜头旋转插值强度", DisplayPriority="75", ClampMin="0.1", ClampMax="100", UIMin="0.1", UIMax="100"))
    float CameraLockedRotationInterp = 4.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="LockedDistanceScale - 锁定时目标距离对臂长的倍率", ToolTip="锁定时目标距离对臂长的倍率", DisplayPriority="76", ClampMin="0", ClampMax="5", UIMin="0", UIMax="5"))
    float CameraDistanceScale = 0.65f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="LockedDistanceBias - 锁定镜头臂长基础偏移 cm", ToolTip="锁定镜头臂长基础偏移 cm", DisplayPriority="77", ClampMin="0", ClampMax="3000", UIMin="0", UIMax="3000"))
    float CameraDistanceBias = 400.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="LockedMinDistance - 锁定镜头最短臂长 cm", ToolTip="锁定镜头最短臂长 cm", DisplayPriority="78", ClampMin="50", ClampMax="3000", UIMin="50", UIMax="3000"))
    float CameraLockedMinDistance = 550.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="LockedMaxDistance - 锁定镜头最长臂长 cm", ToolTip="锁定镜头最长臂长 cm", DisplayPriority="79", ClampMin="50", ClampMax="5000", UIMin="50", UIMax="5000"))
    float CameraLockedMaxDistance = 1000.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="LockedDistanceInterp - 锁定镜头距离插值强度", ToolTip="锁定镜头距离插值强度", DisplayPriority="80", ClampMin="0.1", ClampMax="100", UIMin="0.1", UIMax="100"))
    float CameraLockedDistanceInterp = 3.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="FreeDistanceInterp - 自由镜头距离恢复插值强度", ToolTip="自由镜头距离恢复插值强度", DisplayPriority="81", ClampMin="0.1", ClampMax="100", UIMin="0.1", UIMax="100"))
    float CameraFreeDistanceInterp = 4.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="HideDistance - 近镜头隐藏自身距离 cm", ToolTip="近镜头隐藏自身距离 cm", DisplayPriority="82", ClampMin="0", ClampMax="1000", UIMin="0", UIMax="1000"))
    float CameraHideDistance = 220.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="RevealDistance - 恢复自身显示距离 cm", ToolTip="恢复自身显示距离 cm，须大于HideDistance", DisplayPriority="83", ClampMin="0", ClampMax="1000", UIMin="0", UIMax="1000"))
    float CameraRevealDistance = 270.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="SoftLockRange - 技能辅助朝向目标距离 cm", ToolTip="技能辅助朝向目标距离 cm", DisplayPriority="84", ClampMin="0", ClampMax="10000", UIMin="0", UIMax="10000"))
    float SoftLockRange = 650.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="07 Camera 相机", meta=(DisplayName="SoftLockViewDot - 技能辅助朝向目标视线点积阈值", ToolTip="技能辅助朝向目标视线点积阈值", DisplayPriority="85", ClampMin="-1", ClampMax="1", UIMin="-1", UIMax="1"))
    float SoftLockViewDot = 0.4f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="08 Debug 调试", meta=(DisplayName="Overlay - PIE画面显示配置版本、速度、加速度和Pivot阶段", ToolTip="PIE画面显示配置版本、速度、加速度和Pivot阶段", DisplayPriority="86"))
    bool DebugOverlay = true;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="08 Debug 调试", meta=(DisplayName="MovementVectors - 可视化逻辑移动向量", ToolTip="可视化逻辑移动向量；绿=普通移动目标，黄=Pivot刹车目标，紫=反向加速目标，橙=技能位移，蓝=水平速度", DisplayPriority="87"))
    bool DebugMovementVectors = false;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="08 Debug 调试", meta=(DisplayName="MovementVectorLength - 逻辑移动箭头长度 cm", ToolTip="逻辑移动箭头长度 cm；蓝色速度箭头随速度相对上限缩放", DisplayPriority="88", ClampMin="20", ClampMax="1000", UIMin="20", UIMax="1000"))
    float DebugMovementVectorLength = 180.0f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="08 Debug 调试", meta=(DisplayName="MovementVectorHeight - 箭头起点相对胶囊底部的高度 cm", ToolTip="箭头起点相对胶囊底部的高度 cm", DisplayPriority="89", ClampMin="0", ClampMax="300", UIMin="0", UIMax="300"))
    float DebugMovementVectorHeight = 25.0f;
};
