#pragma once
#include "NativeGameplayTags.h"
namespace CombatTags
{
    COMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Busy);
    COMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
    COMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Invulnerable);
    COMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Parry);
    COMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_RiposteReady);
    COMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stunned);
    COMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Root);
    COMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cue_Hit);
    COMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cue_Parry);
    COMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cue_Evade);
    COMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cue_AreaWarning);
    COMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cue_AreaRelease);
    COMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cue_PoiseBreak);
    COMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cue_Death);
}
