// Type(Member, Section, Key, Default, Min, Max, Description). Also generates the tuning table.
LOCO_FLOAT(ForwardSpeed, Movement, ForwardSpeed, 560, 1, 3000, "前进最高速度 cm/s")
LOCO_FLOAT(BackwardSpeed, Movement, BackwardSpeed, 560, 1, 3000, "后退最高速度 cm/s")
LOCO_FLOAT(LeftSpeed, Movement, LeftSpeed, 560, 1, 3000, "左移最高速度 cm/s")
LOCO_FLOAT(RightSpeed, Movement, RightSpeed, 560, 1, 3000, "右移最高速度 cm/s")
LOCO_FLOAT(Acceleration, Movement, Acceleration, 1600, 1, 20000, "普通移动加速度 cm/s²")
LOCO_FLOAT(GroundFriction, Movement, GroundFriction, 4, 0, 50, "普通移动转向摩擦")
LOCO_FLOAT(BrakingDeceleration, Movement, BrakingDeceleration, 1200, 0, 20000, "松键刹车减速度 cm/s²")
LOCO_FLOAT(BrakingFriction, Movement, BrakingFriction, 0, 0, 50, "松键独立刹车摩擦")
LOCO_FLOAT(BrakingFrictionFactor, Movement, BrakingFrictionFactor, 1, 0, 10, "普通刹车摩擦倍率")
LOCO_FLOAT(TurnRate, Movement, TurnRate, 900, 1, 3600, "自由移动转向角速度 °/s")
LOCO_FLOAT(LockedTurnInterpSpeed, Movement, LockedTurnInterpSpeed, 12, 0.1, 100, "锁定目标时朝向插值速度")
LOCO_FLOAT(InputDeadZone, Movement, InputDeadZone, 0.01, 0, 0.95, "移动输入死区")
LOCO_BOOL(PivotEnabled, Pivot, Enabled, true, "启用折返")
LOCO_FLOAT(PivotMinSpeed, Pivot, MinSpeed, 160, 0, 3000, "折返触发最低水平速度 cm/s")
LOCO_FLOAT(PivotMinAngle, Pivot, MinAngle, 120, 90, 180, "速度与新输入夹角阈值 °")
LOCO_FLOAT(PivotCooldown, Pivot, Cooldown, 0.25, 0, 5, "折返结束或打断后冷却 s")
LOCO_FLOAT(PivotCancelAngle, Pivot, CancelAngle, 60, 1, 180, "新输入偏离折返目标多少度时取消 °")
LOCO_BOOL(PivotCancelOnRelease, Pivot, CancelOnRelease, true, "松键是否取消折返")
LOCO_BOOL(PivotCancelOnLockChange, Pivot, CancelOnLockChange, true, "切换锁定是否取消折返")
LOCO_FLOAT(PivotBrakingDeceleration, Pivot, BrakingDeceleration, 900, 1, 20000, "折返刹车减速度 cm/s²；560速度约0.62秒刹停")
LOCO_FLOAT(PivotBrakingFriction, Pivot, BrakingFriction, 0, 0, 50, "折返刹车附加摩擦；0为纯恒定减速度")
LOCO_FLOAT(PivotStopSpeed, Pivot, StopSpeed, 5, 0, 100, "低于此速度允许切换反向加速 cm/s")
LOCO_FLOAT(PivotReverseAcceleration, Pivot, ReverseAcceleration, 1200, 1, 20000, "折返反向起步加速度 cm/s²")
LOCO_FLOAT(PivotReverseFriction, Pivot, ReverseFriction, 0, 0, 50, "反向加速阶段转向摩擦")
LOCO_FLOAT(PivotReverseDelay, Pivot, ReverseDelay, 0.1, 0, 10, "触发后允许反向起步的最早时间 s")
LOCO_FLOAT(PivotReverseMinProgress, Pivot, ReverseMinProgress, 0, 0, 1, "反向起步所需最小动画进度 0..1")
LOCO_FLOAT(PivotReverseMaxFacingAngle, Pivot, ReverseMaxFacingAngle, 45, 0, 180, "自由移动时朝向距目标小于此角才允许反向起步 °")
LOCO_FLOAT(PivotTurnDelay, Pivot, TurnDelay, 0.02, 0, 10, "触发后延迟多久开始转向 s")
LOCO_FLOAT(PivotTurnRate, Pivot, TurnRate, 900, 1, 3600, "折返转向角速度 °/s；不再绑到整个片段时长")
LOCO_FLOAT(PivotPlayRate, Pivot, PlayRate, 1, 0.05, 4, "完整Pivot片段播放倍率；不会裁剪源片段")
LOCO_FLOAT(PivotBlendIn, Pivot, BlendIn, 0.07, 0, 2, "Pivot进入融合 s；下次触发生效")
LOCO_FLOAT(PivotBlendOut, Pivot, BlendOut, 0.14, 0, 2, "Pivot自然结束融合 s")
LOCO_FLOAT(PivotInterruptBlendOut, Pivot, InterruptBlendOut, 0.08, 0, 2, "Pivot被技能等打断时融合 s")
LOCO_FLOAT(PivotBlendOutTriggerTime, Pivot, BlendOutTriggerTime, 0, -1, 5, "距片尾多久开始融合 s；0播完整段；-1自动")
LOCO_BOOL(PivotEarlyExit, Pivot, EarlyExitEnabled, false, "反向达到速度后是否提前融合回locomotion；默认完整播放")
LOCO_FLOAT(PivotExitMinProgress, Pivot, ExitMinProgress, 0.65, 0, 1, "提前退出所需最小动画进度")
LOCO_FLOAT(PivotExitMinSpeed, Pivot, ExitMinSpeed, 350, 0, 3000, "提前退出所需反向速度 cm/s")
LOCO_FLOAT(AnimationPlayRate, Animation, PlayRate, 1, 0.05, 4, "地面BlendSpace播放倍率；独立于技能和Pivot")
LOCO_FLOAT(AnimationJogSpeed, Animation, JogSpeed, 350, 1, 3000, "真实速度达到此值时到达Jog采样位置 cm/s")
LOCO_FLOAT(AnimationFastSpeed, Animation, FastSpeed, 650, 2, 4000, "真实速度达到此值时到达最高速度采样位置 cm/s")
LOCO_FLOAT(AnimationSpeedInterp, Animation, SpeedInterp, 0, 0, 100, "动画速度参数平滑强度；0立即更新")
LOCO_FLOAT(AnimationDirectionInterp, Animation, DirectionInterp, 0, 0, 100, "动画方向参数平滑强度；0立即更新")
LOCO_FLOAT(AnimationIdleDirectionSpeed, Animation, IdleDirectionSpeed, 5, 0, 100, "低于此速度保持上次动画方向，避免停步抖动 cm/s")
LOCO_FLOAT(JumpVelocity, Air, JumpVelocity, 650, 1, 3000, "起跳速度 cm/s")
LOCO_FLOAT(GravityScale, Air, GravityScale, 1.8, 0.01, 10, "重力倍率")
LOCO_FLOAT(AirControl, Air, AirControl, 0.7, 0, 1, "空中控制比例")
LOCO_FLOAT(AirBrakingDeceleration, Air, BrakingDeceleration, 0, 0, 20000, "空中刹车减速度 cm/s²")
LOCO_FLOAT(AirLateralFriction, Air, LateralFriction, 0, 0, 50, "空中横向摩擦")
LOCO_FLOAT(JumpCount, Air, JumpCount, 2, 1, 10, "最大跳跃次数，取整数")
LOCO_FLOAT(MaxAirHangBudget, Air, MaxHangBudget, 0.25, 0, 2, "空中攻击最大滞空预算 s")
LOCO_FLOAT(PlungeHoldTime, Air, PlungeHoldTime, 0.28, 0, 3, "空中长按攻击触发下劈的时间 s")
LOCO_FLOAT(DashDistance, Dash, Distance, 250, 1, 3000, "闪避移动距离 cm")
LOCO_FLOAT(DashDuration, Dash, Duration, 0.23, 0.01, 0.25, "闪避移动时长 s；上限匹配当前0.255秒技能结束通知")
LOCO_FLOAT(DashDirectionStep, Dash, DirectionStep, 45, 1, 180, "闪避方向量化角度 °")
LOCO_BOOL(StopOnGroundSkill, SkillBlend, StopOnGroundSkill, true, "地面技能开始时是否清零普通移动速度")
LOCO_BOOL(AllowMovementRecovery, SkillBlend, AllowMovementRecovery, true, "总开关：允许移动取消已开放取消窗口的普攻后摇")
LOCO_FLOAT(InputBufferTime, SkillBlend, InputBufferTime, 0.18, 0, 1, "技能输入缓存时间 s")
LOCO_BOOL(OverrideSkillBlendOut, SkillBlend, OverrideBlendOut, true, "由本表覆盖玩家技能结束和打断融合时间")
LOCO_FLOAT(SkillLocomotionBlendOut, SkillBlend, LocomotionBlendOut, 0.14, 0, 2, "玩家技能正常结束回移动的融合时间 s")
LOCO_FLOAT(SkillInterruptBlendOut, SkillBlend, InterruptBlendOut, 0.08, 0, 2, "玩家技能被打断融合时间 s")
LOCO_FLOAT(CameraDistance, Camera, Distance, 560, 50, 3000, "自由镜头距离 cm")
LOCO_FLOAT(CameraOffsetX, Camera, OffsetX, 0, -1000, 1000, "镜头SocketOffset X cm")
LOCO_FLOAT(CameraOffsetY, Camera, OffsetY, 45, -1000, 1000, "镜头SocketOffset Y cm")
LOCO_FLOAT(CameraOffsetZ, Camera, OffsetZ, 85, -1000, 1000, "镜头SocketOffset Z cm")
LOCO_FLOAT(CameraFOV, Camera, FOV, 90, 30, 140, "视野角 °")
LOCO_FLOAT(CameraSensitivity, Camera, Sensitivity, 1, 0.01, 10, "鼠标镜头灵敏度")
LOCO_BOOL(CameraCollision, Camera, Collision, true, "镜头碰撞开关")
LOCO_FLOAT(CameraProbeSize, Camera, ProbeSize, 12, 1, 100, "镜头碰撞探针半径 cm")
LOCO_BOOL(CameraLag, Camera, PositionLag, false, "镜头位置延迟开关")
LOCO_FLOAT(CameraLagSpeed, Camera, PositionLagSpeed, 10, 0.1, 100, "镜头位置延迟跟随速度")
LOCO_BOOL(CameraRotationLag, Camera, RotationLag, false, "镜头旋转延迟开关")
LOCO_FLOAT(CameraRotationLagSpeed, Camera, RotationLagSpeed, 10, 0.1, 100, "镜头旋转延迟跟随速度")
LOCO_FLOAT(CameraLockedTargetWeight, Camera, LockedTargetWeight, 0.4, 0, 1, "锁定构图中心向目标偏移比例")
LOCO_FLOAT(CameraPitchMin, Camera, LockedPitchMin, -35, -89, 89, "锁定镜头最小俯仰角 °")
LOCO_FLOAT(CameraPitchMax, Camera, LockedPitchMax, -8, -89, 89, "锁定镜头最大俯仰角 °")
LOCO_FLOAT(CameraLockedRotationInterp, Camera, LockedRotationInterp, 4, 0.1, 100, "锁定镜头旋转插值强度")
LOCO_FLOAT(CameraDistanceScale, Camera, LockedDistanceScale, 0.65, 0, 5, "锁定时目标距离对臂长的倍率")
LOCO_FLOAT(CameraDistanceBias, Camera, LockedDistanceBias, 400, 0, 3000, "锁定镜头臂长基础偏移 cm")
LOCO_FLOAT(CameraLockedMinDistance, Camera, LockedMinDistance, 550, 50, 3000, "锁定镜头最短臂长 cm")
LOCO_FLOAT(CameraLockedMaxDistance, Camera, LockedMaxDistance, 1000, 50, 5000, "锁定镜头最长臂长 cm")
LOCO_FLOAT(CameraLockedDistanceInterp, Camera, LockedDistanceInterp, 3, 0.1, 100, "锁定镜头距离插值强度")
LOCO_FLOAT(CameraFreeDistanceInterp, Camera, FreeDistanceInterp, 4, 0.1, 100, "自由镜头距离恢复插值强度")
LOCO_FLOAT(CameraHideDistance, Camera, HideDistance, 220, 0, 1000, "近镜头隐藏自身距离 cm")
LOCO_FLOAT(CameraRevealDistance, Camera, RevealDistance, 270, 0, 1000, "恢复自身显示距离 cm，须大于HideDistance")
LOCO_FLOAT(SoftLockRange, Camera, SoftLockRange, 650, 0, 10000, "技能辅助朝向目标距离 cm")
LOCO_FLOAT(SoftLockViewDot, Camera, SoftLockViewDot, 0.4, -1, 1, "技能辅助朝向目标视线点积阈值")
LOCO_BOOL(DebugOverlay, Debug, Overlay, true, "PIE画面显示配置版本、速度、加速度和Pivot阶段")
LOCO_BOOL(DebugMovementVectors, Debug, MovementVectors, false, "可视化逻辑移动向量；绿=普通移动目标，黄=Pivot刹车目标，紫=反向加速目标，橙=技能位移，蓝=水平速度")
LOCO_FLOAT(DebugMovementVectorLength, Debug, MovementVectorLength, 180, 20, 1000, "逻辑移动箭头长度 cm；蓝色速度箭头随速度相对上限缩放")
LOCO_FLOAT(DebugMovementVectorHeight, Debug, MovementVectorHeight, 25, 0, 300, "箭头起点相对胶囊底部的高度 cm")
